### ISSUE TITLE
Sprint 1 Goals

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1297]
- [x] verify connection to MAIS ORCID API
- [x] verify connection to ORCID API
- [x] create client for MAIS ORCID API
- [x] create client for ORCID API
- [x] add profile visibility to authors table and update from Profiles API
- [x] write okcomputer checks for MAIS and ORCID APIs
- [x] document our data schema (our pub hash)
- [x] do mapping between the sul-pub data schema (pub-hash) and ORCID work data schema (Arcadia helping with)
- [x] test push of a few publications to ORCID (but not complete mapping)
- [x] test pull of a few publications from ORCID (not not complete mapping)
- [x] initial effort to locate testing volunteers
