### ISSUE TITLE
Sprint 2 Goals

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1342]
- [x] identify volunteer testers
- [x] identify what we need these testers to do
- [x] identify what we need to verify with data to validate readiness for deployment, i.e. - how many publications do need to push and who will verify?
- [x] identity if we need any humanities faculty for testing (carried over)
- [x] create testing script
