### ISSUE TITLE
Sprint 3 Goals

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#1362]
- [ ] Complete testing of select identified faculty in production (push publications, get feedback)
- [ ] Respond to any bugs/feedback
- [x] identity if we need any humanities faculty for testing (carried over)
