### ISSUE TITLE
Enable author alt-name harvests

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sul_pub#168]
- [x] new PR for unnecessary gem removal: #166
  - merged

shared config PRs:
- [x] sul-dlss/shared_configs#247 for prod
  - not reviewed or merged
  - pending testing on cap-stage and cap-qa
- [x] sul-dlss/shared_configs#248 for cap-qa
  - merged
  - needs to be deployed and file links updated
  - need to review harvesting logs for any errors etc.
- [x] sul-dlss/shared_configs#246 for cap-stage
  - merged
  - needs to be deployed and file links updated
  - need to review harvesting logs for any errors etc.

**Comment by peetucket** [comment]
Tested on -stage and seems to work as expected (for individual author harvesting)
