### ISSUE TITLE
Create a new publication record when we have a new record

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#316]
After the matching logic in #301, if no match is found create a new publication with a pub_hash

Implementing create_publication into process_records class

- [ ] #368 -  Create pub_hash from WoS record using mapping described in #274 or MEDLINE record using mapping in #349
- [ ] #450 - Create new PublicationIdentifiers from rec.identifiers
- [ ] #451 - For WOS-record that has a PMID, fetch data from PubMed and merge new data into pub_hash
- [ ] associate publication with author (i.e. create contribution)

**Comment by darrenleeweber** [comment]
Depends on #333 - `WebOfScience::ProcessRecords#create_publications` is a placeholder for doing this.
