### ISSUE TITLE
Final release deployment to production checklist

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul_pub#521]
**On deploy date:**
- [x] backup mysql prod (happens nightly automatically)
- [x] update shared config files are on  -prod (e.g. WoS API keys, feature flag set correctly)
  `bundle exec cap prod shared_configs:update`
- [x] deploy master to prod
  `bundle exec cap prod deploy`
- [x] confirm crontab has new WoS API harvesting job on prod
- [ ] test manual publication creation search and creation (i.e. searching works and adding a search result to a profile works with the second API callback)
  - [x] by **PMID** for a publication  
    - [x] currently in our database (pmid = 28830582, sul_pub_id = 457928)
    - [x] not currently in our database (some examples, can only be used once of course, pmid = 28912577, 28245323, 25355167) 
  - [x] by **title** for a publication 
    - [x] currently in our database ("Noise power spectra of images from digital mammography detectors", sul_pub_id = 248211, pmid = 10435530)
    - [x] not currently in our database
  - [x] by **DOI** for a publication 
    - [x] currently in our database (doi = 10.1016/j.jbi.2017.02.004, sul_pub_id = 437647)
    - [x] not currently in our database (some examples, can only be used once of course, doi = 10.1101/cshperspect.a029652, 10.1053/j.seminoncol.2013.09.012, 10.1055/s-0042-119809)
  - [ ] entirely manual entry publication
  - [x] do a manual harvest for some specific profiles and pull them:
   `RAILS_ENV=production bundle exec rake wos:harvest_author[4706,'16week'] # 20 new`
   `RAILS_ENV=production bundle exec rake wos:harvest_author[4188,'16week'] # 2 new`   
   `RAILS_ENV=production bundle exec rake wos:harvest_author[8040,'16week'] # 2 new`
   `RAILS_ENV=production bundle exec rake wos:harvest_author[10119,'16week'] # 1 new`
   `RAILS_ENV=production bundle exec rake wos:harvest_author[58973,'16week'] # 0 new `
   `RAILS_ENV=production bundle exec rake wos:harvest_author[187833,'16week'] # 3 new`
   `RAILS_ENV=production bundle exec rake wos:harvest_author[86111,'16week'] # 6 new`
   `RAILS_ENV=production bundle exec rake wos:harvest_author[183229,'16week'] # 6 new`
   `RAILS_ENV=production bundle exec rake wos:harvest_author[145591,'16week'] # 0 new`
   `RAILS_ENV=production bundle exec rake wos:harvest_author[70975,'16week'] # 2 new`
  - [x] have Profiles team pull somenew publications onto user's profiles and confirm

**Day after:**
- [ ] run full harvest against WOS going back 12 weeks in screen
  `RAILS_ENV=production bundle exec rake wos:harvest_authors_update['12week']`
- [ ] confirm we can update some of those new publications (accept/reject/highlight) via API calls from Profiles side
- [x] confirm `OKcomputer` checks and notifications are set up for new WoS API and disabled for Sciencewire

**Later:**
- [ ] spot check some of the new publications to check for obvious false positives
- [ ] run identifier normalization script: 
  `RAILS_ENV=production bundle exec rails runner script/publication_identifier_normalization.rb`
- [ ] double-check free disk space on prod

**Rollback Plan If Needed to Go to old SW code:**
- [ ] Undo the migration that is incompatible between new and old code (removal of identity_type column in author_identities):
  `RAILS_ENV=production bundle exec rake db:migrate:down VERSION=20180224013914`
- [ ] Rollback the release:
  `cap prod deploy:rollback`
- [ ] Double check the crontab on prod to be sure it does not have wos harvesting enabled.  To update cron automatically from whenever, go to the prod server:
 `bundle exec whenever --update-crontab`
- [ ] Double check settings.yml

**Comment by atz** [comment]
Remember those harvests *cannot* be broadly parallelized given WoS upstream throttling.

**Comment by peetucket** [comment]
Yup. Since it’s only 10 and each shouldn’t take too long we can just run them sequentially.
